version: '3.5'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
    # environment:
    #   - ELASTICSEARCH_USERNAME=admin
    #   - ELASTICSEARCH_PASSWORD=admin@123
    # environment:
      # - cluster.name=docker-cluster
      # - bootstrap.memory_lock=true
      # - xpack.security.enabled=false
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
      - target: 9300
        published: 9300
        protocol: tcp
        mode: host

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.3
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports: 
      - target: 5601
        published: 5601
        protocol: tcp
        mode: host
    depends_on:
      - elasticsearch
  logstash:
    image: docker.elastic.co/logstash/logstash:6.5.3
    volumes:
      - ./file/logstash_back.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - target: 5043
        published: 5043
        protocol: tcp
        mode: host
      - target: 9600
        published: 9600
        protocol: tcp
        mode: host
    depends_on:
      - elasticsearch
   
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.5.3
    depends_on:
      - logstash
    volumes:
      - ./file/filebeat_back.yml:/usr/share/filebeat/filebeat.yml
      - ./logs/:/home/logs/